# Generated by Django 4.2.6 on 2023-11-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_code', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=50)),
                ('goods_price', models.IntegerField(blank=True, null=True)),
                ('goods_description', models.CharField(max_length=255)),
                ('goods_category', models.IntegerField()),
                ('goods_img_path', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'goods',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('detail_code', models.AutoField(primary_key=True, serialize=False)),
                ('volume', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('fiber', models.IntegerField()),
                ('allergies', models.CharField(max_length=19)),
                ('goods_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
            ],
            options={
                'db_table': 'goods_detail',
                'managed': True,
            },
        ),
    ]
