# Generated by Django 4.2.6 on 2023-11-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_goodsdetail_goods_code_goodsdetail_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetail',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodsdetail', to='goods.goods'),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='volume',
            field=models.IntegerField(db_column='volume'),
        ),
    ]
