# Generated by Django 4.2.6 on 2023-11-09 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_code', models.AutoField(db_column='member_Code', primary_key=True, serialize=False)),
                ('member_name', models.CharField(db_column='member_Name', max_length=20)),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=20)),
                ('grade', models.IntegerField()),
                ('member_point', models.IntegerField()),
                ('joindate', models.DateTimeField(db_column='joinDate')),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentcode', models.AutoField(db_column='paymentCode', primary_key=True, serialize=False)),
                ('storecode', models.IntegerField(db_column='storeCode')),
                ('paymentprice', models.IntegerField(db_column='paymentPrice')),
                ('paymentdate', models.DateTimeField(db_column='paymentDate')),
                ('membercode', models.ForeignKey(db_column='memberCode', on_delete=django.db.models.deletion.DO_NOTHING, to='members.member')),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
    ]
