# Generated by Django 4.2.6 on 2023-11-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_code', models.AutoField(db_column='grade_code', primary_key=True, serialize=False)),
                ('grade_name', models.CharField(db_column='grade_name', max_length=20)),
                ('point_rate', models.IntegerField(db_column='point_rate')),
                ('base_amount', models.IntegerField(db_column='base_amount')),
                ('grade_img', models.CharField(db_column='grade_img', max_length=1000)),
            ],
            options={
                'db_table': 'grade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_code', models.AutoField(db_column='store_code', primary_key=True, serialize=False)),
                ('store_name', models.CharField(db_column='store_name', max_length=20)),
                ('store_address', models.CharField(db_column='store_address', max_length=255)),
                ('store_phone', models.CharField(db_column='store_phone', max_length=20)),
            ],
            options={
                'db_table': 'store',
                'managed': True,
            },
        ),
    ]
