# Generated by Django 4.2.6 on 2023-11-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_grade_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_code',
            new_name='memberCode',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_point',
            new_name='point',
        ),
    ]
