# Generated by Django 4.2.6 on 2023-11-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_member_code_member_membercode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='memberCode',
            new_name='member_code',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='member_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='point',
            new_name='member_point',
        ),
    ]
